const data = {
    products: [
        {
            name: 'Pink and Beige Georgette Indian Saree With Blouse',
            category: 'Women',
            image: '/images/w1.jpg',
            price: 1250,
            countInStock: 10,
            brand: 'Viva',
            material: 'Polycotton',
            size: 34,
            rating: 3.5,
            numReviews: 10,
            description:
                'Saree DetailsParty Wear SareesSaree Color - Pink and BeigeSaree Material - GeorgetteSaree Work - Lace Border , Zari Work , Stone WorkSaree Size - Approx 6 Yards Long(Length 548cm x Width 112cm)Fall & Edging Complimentary with this ProductSaree Blouse DetailSaree Blouse Color - PinkSaree Blouse Material - Dupion Silk , NetSaree Blouse Size - Apprrox - 0.88 Yards Long(Length 80cm x Width 112 cm)More DetailSaree will reach to you in Maximum 8 - 10 working days.Care - Dry Clean Only.Each Product may vary slightly in tint or shade from the actual screw cover due to uncontrollaBle variations in monitor resolution.',
        },
        {
            name: 'AH Arctic Hunter,',
            category: 'Men',
            image: '/images/m6.jpg',
            price: 99,
            countInStock: 7,
            brand: 'Applique',
            material: 'Synthetic',
            size: 32,
            rating: 4.5,
            numReviews: 25,
            description:
                'eparate laptop compartment hold 15.6 Inch Laptop as well as 15 Inch,14 Inch and 13 Inch Macbook/Laptop. Spacious packing compartment for daily Luch box and clothing.Third compartment with many small pockets for necessities,electronics ,pen and key fob hook, make your items organized and easier to find. ',
        },

        {
            name: 'Bollywood Salwar Kameez – Buy Bollywood Suits Online Shopping',
            category: 'Women',
            image: '/images/w2.jpeg',
            price: 1823,
            countInStock: 20,
            brand: 'Polka',
            material: 'Cotton',
            size: 28,
            rating: 2.5,
            numReviews: 10,
            description:
                'Shop Latest Collection of Bollywood Salwar Kameez Online. Buy from a Wide Variety of Bollywood Salwar Suits Online | Free Shipping',
        },
        {
            name: 'Buy Indian Sarees Online | Designer Saris USA | Latest Saree Shopping Canada',
            category: 'Women',
            image: '/images/w3.jpeg',
            price: 720,
            countInStock: 2,
            brand: 'Janasya',
            material: 'Fabric',
            size: 42,
            rating: 1.5,
            numReviews: 17,
            description:
                'Looking to shop the latest collection of Indian party wear designer sarees online in USA, Canada, Australia, New Zealand, or worldwide? At Sarees Bazaar you can find a stylish range of traditional silk sarees, wedding bridal saree designs, casual printed saree, and lot more with express shipping from India with an additional discount and free shipping offers.',
        },
        {
            name: 'TEmbroidered Peach Color Silk Sari',
            category: 'Women',
            image: '/images/w4.jpeg',
            price: 1428,
            countInStock: 15,
            brand: 'Floral',
            material: 'Synthetic',
            size: 36,
            rating: 5,
            numReviews: 14,
            description:
                'Description Create an aura of elegance this festive season stepping out in this peach color embroidered silk sari. That you can see some interesting patterns accomplished with lace and resham work. Upon request we can make round front/back neck and short 6 inches sleeves regular saree blouse also. Material: Poly Silk Fit: Not Applicable Neck Line: Fancy Workmanship: Embroidred Lining: Art Silk Co-Ordinates: None Hem: Not Applicable Care: Dry Clean Only',
        },
        {
            name: 'ZOUK BWhite Arrow Handmade',
            category: 'Men',
            image: '/images/m7.jpg',
            price: 1600,
            countInStock: 12,
            brand: 'Duke',
            material: 'Cotton',
            size: 38,
            rating: 4.5,
            numReviews: 15,
            description:
                'Our Stylish Office Bag For Women Is An Ideal Laptop Bag, Handbag Or A Professional Bag. It Can Fit A Laptop Of Upto 15.6 Inches And Is Perfect For Macbook, Chromebook, Ipad, Tablet, Hp, Lenovo, Dell Etc. Dimensions: 18 X 13 X 4 Inch',
        },
        {
            name: 'Designer Salwar kameez | Designer Punjab Suits | Pakistani Salwar Kameez',
            category: 'Women',
            image: '/images/w5.jpeg',
            price: 2054,
            countInStock: 5,
            brand: 'Shonaya',
            material: 'Cotton Blend',
            size: 34,
            rating: 3.5,
            numReviews: 10,
            description:
                '3 Piece Embroidered Unstitched Suits from Imrozia Solas de Lune Manufacturer: Serene Premium Shirt Fabric: Chiffon Catalog: Imrozia Solas de Lune 2020 Collection',
        },
        {
            name: "Women's Ethnic Dresses: Shop for Designer Sarees, Suits, Lehengas Online | Andaazfashion.com.my",
            category: 'Women',
            image: '/images/w6.jpeg',
            price: 1780,
            countInStock: 12,
            brand: 'Polka',
            material: 'Cotton',
            size: 38,
            rating: 4,
            numReviews: 15,
            description:
                'Andaazfashion.com.my: Buy from the latest collection of Indian ethnic outfits, dresses & designer clothes for women. Shop with confidence with our Satisfaction Guaranteed.',
        },

        {
            name: 'Emma',
            category: 'Women',
            image: '/images/w7.jpg',
            price: 925,
            countInStock: 12,
            brand: 'Floral',
            material: 'Fabric',
            size: 40,
            rating: 1.5,
            numReviews: 15,
            description:
                'Shirt: Pure chiffon long silhouette shirt featuring Antique gold dabka, sequins, gota, pearls, beads and contrasting silk thread embroidery, stylish net sleeves and net applique on neckline and hem. Shirt Color: Maroon Shirt Length 48” Pant: Pure Raw Silk straight Pants Pant Color: Maroon Dupatta: Pure chiffon dupatta with sequins and beads studded border followed by sequin sprinkle all over. Dupatta Color: Antique Brass All outfits are fully lined. Lining in sleeves is complimentary just mention in custom text box if needed Please refer Size Chart Before selecting size Shirt and Pant can be ordered in different sizes, mention in custom text box if required (For Customized measurements please select Custom size for an additional 20$ charges per outfit ) Prices mentioned are of stitched full outfit (inclusive of pant and dupatta) Colors may slightly vary from picture Dry Clean Only Model is 5’5” and wearing a size XS',
        },
        {
            name: 'Celestia Regular',
            category: 'Women',
            image: '/images/w8.jpg',
            price: 1348,
            countInStock: 7,
            brand: 'Woven',
            material: 'Polycotton',
            size: 40,
            rating: 2.5,
            numReviews: 15,
            description:
                'Shirt: Pure Raw silk long straight silhouette shirt featuring traditional antique gold dabka, sequins, crystal, tilla, 3D beadwork and contrasting color silk thread embroidery. Shirt Color: Chocolate Brown Shirt Length 45” Pant: Pure Self design soft tissue culottes featuring beadwork on hem. Pant Color: Chocolate brown and Gold Culottes Length : 35" (XS/S) ,36" (M/L) , 37" (XL) (can be customize mention in custom box if required ) Dupatta: Pure chiffon dupatta with beadwork motifs finished with gota, sea green and brown edging. Dupatta Color: Pistachio Green All outfits are fully lined. Lining in sleeves is complimentary just mention in custom text box if needed Please refer Size Chart Before selecting size Shirt and Pant can be ordered in different sizes, mention in custom text box if required (For Customized measurements please select Custom size for an additional 20$ charges per outfit ) Prices mentioned are of stitched full outfit (inclusive of pant and dupatta) Colors may slightly vary from picture Dry Clean Only Model is 5’5” and wearing a size XS',
        },
        {
            name: "Ma Croix Men's Mesh",
            category: 'Men',
            image: '/images/m2.jpeg',
            price: 39,
            countInStock: 7,
            brand: 'Divastri',
            material: 'Cotton',
            size: 28,
            rating: 1.5,
            numReviews: 25,
            description:
                'Mesh Shorts that’s brought to you at bargain price; in many colors; provides comfort, utility, and durability into one package. Shorts that can be used in any and all situations. Go running and these shorts are sure not to absorb any moisture.',
        },
        {
            name: 'Robe jesta',
            category: 'Women',
            image: '/images/w10.jpg',
            price: 39,
            countInStock: 0,
            brand: 'Applique',
            material: 'Synthetic',
            size: 38,
            rating: 5,
            numReviews: 11,
            description:
                "Imaginée dans une coupe fittée et fluide, la robe Jesta porte un motif fleuri et aux inspirations cachemire. Douce et confortable, elle s'adapte à toutes vos envies de style: associée à un jean, elle sera décontractée. Portée sur une jupe en crêpe noire, elle orne un côté féminin et plus distingué.",
        },
        {
            name: 'Graphic Print Men Round Neck Blue T-Shirt',
            category: 'Men',
            image: '/images/m1.jpeg',
            price: 1029,
            countInStock: 2,
            brand: ' Duke',
            material: 'Cotton Blend',
            size: 28,
            rating: 2.5,
            numReviews: 15,
            description: "WSEVYPO Men's 3/4 Jogger Capri Pants Sport Shorts Running Trouser With",
        },

        {
            name: "Woman's Capilene",
            category: 'Women',
            image: '/images/w11.jpg',
            price: 67,
            countInStock: 12,
            brand: 'Viva',
            material: 'Cotton',
            size: 28,
            rating: 4.5,
            numReviews: 4,
            description:
                'Легкие и эластичные брюки Nike Dri-FIT позволяют играть весь матч в полном комфорте. Благодаря немного зауженному крою и заниженному шаговому шву эту повседневную модель в уличном стиле можно использовать в разных образах для любой ситуации.',
        },
        {
            name: 'Zainab Chottani Azal 1a Chikankari 2022',
            category: 'Women',
            image: '/images/w12.jpg',
            price: 37,
            countInStock: 4,
            brand: 'Janasya',
            material: 'Cotton Blend',
            size: 28,
            rating: 1,
            numReviews: 8,
            description:
                'Zainab Chottani Azal 1a Chikankari 2022 Original brand suit fabric and photography lite diffrance in actual print.',
        },
        {
            name: 'Gul Ahmed CL-1334 Lawn Essential 2022',
            category: 'Women',
            image: '/images/w13.jpg',
            price: 2123,
            countInStock: 12,
            brand: 'Duke',
            material: 'Fabric',
            size: 26,
            rating: 5,
            numReviews: 15,
            description:
                'Gul Ahmed CL-1334 Lawn Essential Original brand suit fabric and photography lite diffrance in actual print.',
        },
        {
            name: 'Sana Safinaz Collection Online | Buy Original Sana Safinaz Fabric',
            category: 'Women',
            image: '/images/w14.jpg',
            price: 20,
            countInStock: 12,
            brand: 'Paisley',
            material: 'Fabric',
            size: 32,
            rating: 3.5,
            numReviews: 15,
            description:
                'Browse through a wide range of the Latest and most trendiest Sana Safinaz Designer Dresses. Shop Sana Safinaz Collection Online across the globe.',
        },

        {
            name: 'Striped Men Round Neck Light Green, Black T-Shirt',
            category: 'Men',
            image: '/images/m3.jpeg',
            price: 929,
            countInStock: 12,
            brand: 'Paisley',
            material: 'Polycotton',
            size: 28,
            rating: 4.5,
            numReviews: 15,
            description:
                'Fanideaz Men’s Half Sleeve Cotton Denim Blue Striped Polo T Shirt with Branded Logo Embroidery',
        },

        {
            name: 'Wesley Milestone',
            category: 'Men',
            image: '/images/m4.jpg',
            price: 739,
            countInStock: 7,
            brand: 'Floral',
            material: 'Synthetic',
            size: 40,
            rating: 3.5,
            numReviews: 25,
            description:
                'Wesley Milestone 15.6 inch 25 L Casual Waterproof Laptop Backpack/Office Bag/School Bag/College Bag/Business Bag/Unisex Travel Backpack',
        },
        {
            name: 'Lenovo Slim Everyday Backpack',
            category: 'Men',
            image: '/images/m5.jpg',
            price: 1139,
            countInStock: 12,
            brand: 'Woven',
            material: 'Cotton',
            size: 30,
            rating: 5.5,
            numReviews: 15,
            description:
                'Slim, compact & sturdy: Minimal and compact design for professionals: Joint material design, durable, water-resistant polyester material. The padded shoulder straps, handle, and back panel provides protection and all-day comfort',
        },

        {
            name: "Croix Men's Mesh  ",
            category: 'Bags',
            image: '/images/m8.jpg',
            price: 1725,
            countInStock: 7,
            brand: 'Divastri',
            material: 'Cotton',
            size: 28,
            rating: 2.5,
            numReviews: 25,
            description:
                'Mesh Shorts that’s brought to you at bargain price; in many colors; provides comfort, utility, and durability into one package. Shorts that can be used in any and all situations. Go running and these shorts are sure not to absorb any moisture.',
        },
    ],
};

module.exports = data;
